version: "3.7"

services:
  smtp:
    # Remote
    # image: laimison/exim-relay

    # Or local
    build:
      context: .
      dockerfile: Dockerfile

    # Comment out to use default or uncomment and run: exim -bdf -q15m
    # entrypoint: >
    #   sh -c "sleep 100000000"

    container_name: smtp
    hostname: smtp
    user: 100:101
    restart: always
    ports:
      - "1025:8025"
    environment:
      - HOSTNAME=my.host.name
      - SMARTHOST=smtp.gmail.com::587
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - RELAY_FROM_HOSTS=10.0.0.0/8:172.16.0.0/12:192.168.0.0/16
      - RELAY_TO_DOMAINS=yahoo.com:gmail.com
