{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: smtp-relay
  namespace: {{ .Values.namespace }}
spec:
  egress:
  {{- range .Values.networkPolicy.allowedNamespaces }}
  - to:
    - namespaceSelector:
        matchLabels:
          purpose: {{ . }}
  {{- end }}
  {{- range .Values.networkPolicy.externalIps }}
  - to:
    - ipBlock:
        cidr: {{ . }}
  {{- end }}
  ingress:
  - from:
  {{- range .Values.networkPolicy.allowedNamespaces }}
    - namespaceSelector:
        matchLabels:
          purpose: {{ . }}
  {{- end }}
  podSelector:
    matchLabels:
      {{- include "smtp-relay.fixed-labels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
{{- end }}
