apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtp-relay.fullname" . }}
  namespace: {{ .Values.namespace }}
  annotations:
        {{- toYaml .Values.service.annotations | trim | nindent 4 }}
  labels:
        {{- include "smtp-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
        {{- if eq .Values.service.type "LoadBalancer" }}
  externalTrafficPolicy: "Local"
        {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8025
      protocol: TCP
      name: smtp
  selector:
    app.kubernetes.io/name: {{ include "smtp-relay.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
